import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '@/hooks/useLanguage';
import { useTheme } from '@/hooks/useTheme';
import toolAPI from '@/services/api/toolAPI';
import { ArrowLeft, Save, Plus, Trash2, Play, Check, X, Loader2 } from 'lucide-react';
export default function CreateToolPage() {
  const { t } = useLanguage(); const { isDark } = useTheme(); const navigate = useNavigate();
  const [saving, setSaving] = useState(false); const [testing, setTesting] = useState(false); const [testResult, setTestResult] = useState(null);
  const [form, setForm] = useState({ name:'', description:'', functionName:'', type:'custom_http', httpConfig:{method:'GET',url:'',headers:[],bodyTemplate:'',timeout:10000,responseMapping:''}, parameters:[], behavior:{waitingMessage:'جاري البحث...',failureMessage:'عذراً، حدث خطأ.'} });
  const handleSave = async () => { try { setSaving(true); await toolAPI.create(form); navigate('/tools'); } catch(e){alert(e.message)} finally{setSaving(false)} };
  const handleTest = async () => { try { setTesting(true); setTestResult(null); const res = await toolAPI.test(form); setTestResult(res.data?.data); } catch(e){setTestResult({success:false,error:e.message})} finally{setTesting(false)} };
  const addParam = () => setForm(p=>({...p,parameters:[...p.parameters,{name:'',type:'string',description:'',required:false,enumValues:[]}]}));
  const removeParam = (i) => setForm(p=>({...p,parameters:p.parameters.filter((_,idx)=>idx!==i)}));
  const updateParam = (i,k,v) => setForm(p=>({...p,parameters:p.parameters.map((param,idx)=>idx===i?{...param,[k]:v}:param)}));
  const card = isDark ? 'bg-[#111113] border-[#1f1f23]' : 'bg-white border-gray-200';
  const text = isDark ? 'text-white' : 'text-gray-900'; const textSec = isDark ? 'text-gray-400' : 'text-gray-600'; const textMuted = isDark ? 'text-gray-500' : 'text-gray-500';
  const inputCls = `w-full rounded-xl px-4 py-2.5 border focus:border-teal-500 focus:outline-none ${isDark ? 'bg-[#1a1a1d] border-[#27272a] text-white' : 'bg-white border-gray-300 text-gray-900'}`;
  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6"><div className="flex items-center gap-3"><button onClick={()=>navigate('/tools')} className={`p-2 rounded-lg ${isDark?'hover:bg-[#1a1a1d]':'hover:bg-gray-100'}`}><ArrowLeft size={20} className={textSec}/></button><h1 className={`text-2xl font-bold ${text}`}>{t('tools.createTool')}</h1></div><div className="flex gap-3"><button onClick={handleTest} disabled={testing} className={`flex items-center gap-2 px-4 py-2 rounded-xl border ${isDark?'border-[#1f1f23] text-gray-400 hover:bg-[#1a1a1d]':'border-gray-200 text-gray-600 hover:bg-gray-50'}`}>{testing?<Loader2 size={16} className="animate-spin"/>:<Play size={16}/>} {t('tools.test.run')}</button><button onClick={handleSave} disabled={saving} className="flex items-center gap-2 px-5 py-2 bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-400 hover:to-cyan-400 text-white font-bold rounded-xl disabled:opacity-50">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>} {t('common.save')}</button></div></div>
      <div className="space-y-6">
        <section className={`rounded-2xl p-6 border ${card}`}><h2 className={`text-lg font-semibold mb-4 ${text}`}>معلومات الأداة</h2><div className="grid gap-4"><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('tools.toolName')}</label><input value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} className={inputCls}/></div><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('tools.description')}</label><textarea value={form.description} onChange={e=>setForm(p=>({...p,description:e.target.value}))} rows={2} className={`${inputCls} resize-none`}/></div><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('tools.functionName')}</label><input value={form.functionName} onChange={e=>setForm(p=>({...p,functionName:e.target.value}))} className={`${inputCls} font-mono`} dir="ltr" placeholder="get_weather"/></div></div></section>
        <section className={`rounded-2xl p-6 border ${card}`}><h2 className={`text-lg font-semibold mb-4 ${text}`}>{t('tools.http.title')}</h2><div className="grid gap-4"><div className="grid grid-cols-4 gap-3"><div><label className={`block text-sm mb-1 ${textMuted}`}>Method</label><select value={form.httpConfig.method} onChange={e=>setForm(p=>({...p,httpConfig:{...p.httpConfig,method:e.target.value}}))} className={inputCls}><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select></div><div className="col-span-3"><label className={`block text-sm mb-1 ${textMuted}`}>URL</label><input value={form.httpConfig.url} onChange={e=>setForm(p=>({...p,httpConfig:{...p.httpConfig,url:e.target.value}}))} className={`${inputCls} font-mono`} dir="ltr" placeholder={t('tools.http.urlPlaceholder')}/></div></div><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('tools.http.bodyHint')}</label><textarea value={form.httpConfig.bodyTemplate} onChange={e=>setForm(p=>({...p,httpConfig:{...p.httpConfig,bodyTemplate:e.target.value}}))} rows={3} className={`${inputCls} font-mono text-sm resize-none`} dir="ltr"/></div></div></section>
        <section className={`rounded-2xl p-6 border ${card}`}><div className="flex items-center justify-between mb-4"><h2 className={`text-lg font-semibold ${text}`}>{t('tools.parameters.title')}</h2><button onClick={addParam} className="flex items-center gap-1 px-3 py-1.5 bg-teal-500/10 text-teal-400 border border-teal-500/20 rounded-xl text-sm"><Plus size={14}/> {t('tools.parameters.add')}</button></div>{form.parameters.map((p,i)=>(<div key={i} className={`grid grid-cols-4 gap-3 p-3 rounded-xl mb-2 ${isDark?'bg-[#0a0a0b]':'bg-gray-50'}`}><input value={p.name} onChange={e=>updateParam(i,'name',e.target.value)} className={inputCls} placeholder={t('tools.parameters.name')}/><select value={p.type} onChange={e=>updateParam(i,'type',e.target.value)} className={inputCls}><option value="string">String</option><option value="number">Number</option><option value="boolean">Boolean</option></select><input value={p.description} onChange={e=>updateParam(i,'description',e.target.value)} className={inputCls} placeholder={t('tools.parameters.paramDescription')}/><button onClick={()=>removeParam(i)} className={`p-2 rounded-lg self-center ${isDark?'hover:bg-red-500/10':'hover:bg-red-50'}`}><Trash2 size={16} className="text-red-400"/></button></div>))}</section>
        {testResult&&<div className={`rounded-2xl p-4 border ${testResult.success?(isDark?'bg-emerald-500/10 border-emerald-500/30':'bg-emerald-50 border-emerald-200'):(isDark?'bg-red-500/10 border-red-500/30':'bg-red-50 border-red-200')}`}><div className="flex items-center gap-2 text-sm">{testResult.success?<><Check size={16} className="text-emerald-400"/><span className="text-emerald-400">{t('tools.test.success')}</span></>:<><X size={16} className="text-red-400"/><span className="text-red-400">{t('tools.test.failed')}: {testResult.error}</span></>}</div></div>}
      </div>
    </div>
  );
}
