import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useLanguage } from '@/hooks/useLanguage';
import { useTheme } from '@/hooks/useTheme';
import knowledgeAPI from '@/services/api/knowledgeAPI';
import { ArrowLeft, Upload, Trash2, Search, FileText, Globe, MessageCircle, Loader2, CheckCircle, XCircle, Clock } from 'lucide-react';
const STATUS_ICONS = { pending:<Clock size={16} className="text-yellow-400"/>, processing:<Loader2 size={16} className="text-cyan-400 animate-spin"/>, ready:<CheckCircle size={16} className="text-emerald-400"/>, failed:<XCircle size={16} className="text-red-400"/> };
const SOURCE_ICONS = { file:<FileText size={16}/>, url:<Globe size={16}/>, faq:<MessageCircle size={16}/>, text:<FileText size={16}/> };
export default function KnowledgeBasePage() {
  const { id } = useParams(); const { t } = useLanguage(); const { isDark } = useTheme(); const navigate = useNavigate(); const fileInputRef = useRef(null);
  const [base, setBase] = useState(null); const [documents, setDocuments] = useState([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [activeTab, setActiveTab] = useState('documents');
  const [faqQ, setFaqQ] = useState(''); const [faqA, setFaqA] = useState(''); const [urlInput, setUrlInput] = useState('');
  const [searchQuery, setSearchQuery] = useState(''); const [searchResults, setSearchResults] = useState([]); const [searching, setSearching] = useState(false);
  useEffect(() => { loadData(); }, [id]);
  const loadData = async () => { try { setLoading(true); const [b, d] = await Promise.all([knowledgeAPI.getBase(id), knowledgeAPI.getDocuments(id)]); setBase(b.data?.data); setDocuments(d.data?.data || []); } catch(e){console.error(e)} finally{setLoading(false)} };
  const handleFileUpload = async (e) => { const files = e.target.files; if (!files?.length) return; setUploading(true); try { for (const file of files) { const res = await knowledgeAPI.uploadDocument(id, file); setDocuments(prev => [res.data?.data, ...prev]); } } catch(e){alert(e.message)} finally { setUploading(false); if(fileInputRef.current) fileInputRef.current.value=''; } };
  const handleAddUrl = async () => { if(!urlInput.trim()) return; try { const res = await knowledgeAPI.addUrl(id, urlInput.trim()); setDocuments(prev=>[res.data?.data,...prev]); setUrlInput(''); } catch(e){alert(e.message)} };
  const handleAddFaq = async () => { if(!faqQ.trim()||!faqA.trim()) return; try { const res = await knowledgeAPI.addFaq(id, faqQ.trim(), faqA.trim()); setDocuments(prev=>[res.data?.data,...prev]); setFaqQ(''); setFaqA(''); } catch(e){alert(e.message)} };
  const handleDeleteDoc = async (docId) => { if(!confirm(t('common.confirm'))) return; try { await knowledgeAPI.deleteDocument(docId); setDocuments(prev=>prev.filter(d=>d.id!==docId)); } catch(e){console.error(e)} };
  const handleSearch = async () => { if(!searchQuery.trim()) return; setSearching(true); try { const res = await knowledgeAPI.search(searchQuery.trim(), 5); setSearchResults(res.data?.data || []); } catch(e){console.error(e)} finally{setSearching(false)} };
  const card = isDark ? 'bg-[#111113] border-[#1f1f23]' : 'bg-white border-gray-200';
  const text = isDark ? 'text-white' : 'text-gray-900'; const textSec = isDark ? 'text-gray-400' : 'text-gray-600'; const textMuted = isDark ? 'text-gray-500' : 'text-gray-500';
  const inputCls = `w-full rounded-xl px-4 py-2.5 border focus:border-teal-500 focus:outline-none ${isDark ? 'bg-[#1a1a1d] border-[#27272a] text-white' : 'bg-white border-gray-300 text-gray-900'}`;
  const tabCls = (active) => `px-4 py-2 rounded-xl text-sm border transition ${active ? 'bg-teal-500/10 text-teal-500 border-teal-500/20' : isDark ? 'bg-[#1a1a1d] border-[#1f1f23] text-gray-400 hover:text-white' : 'bg-white border-gray-200 text-gray-600 hover:text-gray-900'}`;
  if (loading) return <div className="flex items-center justify-center h-64"><Loader2 className={`animate-spin ${textSec}`} size={32}/></div>;
  if (!base) return <div className={`p-6 text-center ${textSec}`}>{t('knowledge.empty.title')}</div>;
  return (
    <div className="p-6 max-w-5xl mx-auto">
      <div className="flex items-center gap-3 mb-6"><button onClick={()=>navigate('/knowledge')} className={`p-2 rounded-lg ${isDark?'hover:bg-[#1a1a1d]':'hover:bg-gray-100'}`}><ArrowLeft size={20} className={textSec}/></button><div><h1 className={`text-2xl font-bold ${text}`}>{base.name}</h1>{base.description&&<p className={`text-sm ${textMuted}`}>{base.description}</p>}</div></div>
      <div className="grid grid-cols-3 gap-4 mb-6">{[{v:base.totalDocuments,l:t('knowledge.documents.title')},{v:base.totalChunks,l:'أجزاء'},{v:base.totalTokens?.toLocaleString(),l:'توكنز'}].map((s,i)=>(<div key={i} className={`rounded-2xl p-4 border text-center ${card}`}><div className={`text-2xl font-bold ${text}`}>{s.v}</div><div className={`text-sm ${textMuted}`}>{s.l}</div></div>))}</div>
      <div className="flex gap-2 mb-6">{['documents','upload','url','faq','search'].map(tab=>(<button key={tab} onClick={()=>setActiveTab(tab)} className={tabCls(activeTab===tab)}>{tab==='documents'?t('knowledge.documents.title'):tab==='upload'?t('knowledge.documents.upload'):tab==='url'?t('knowledge.documents.addUrl'):tab==='faq'?t('knowledge.documents.addFaq'):t('knowledge.search.title')}</button>))}</div>
      {activeTab==='documents'&&(<div className="space-y-3">{documents.length===0?<div className={`text-center py-12 ${textMuted}`}>{t('common.noData')}</div>:documents.map(doc=>(<div key={doc.id} className={`flex items-center justify-between rounded-2xl p-4 border ${card}`}><div className="flex items-center gap-3"><span className={textMuted}>{SOURCE_ICONS[doc.sourceType]}</span><div><div className={`font-medium ${text}`}>{doc.fileName||doc.sourceUrl||doc.faqQuestion||'Document'}</div><div className={`flex items-center gap-2 text-xs mt-1 ${textMuted}`}>{STATUS_ICONS[doc.status]}<span>{doc.status}</span>{doc.totalChunks>0&&<span>• {doc.totalChunks} chunks</span>}</div>{doc.errorMessage&&<div className="text-xs text-red-400 mt-1">{doc.errorMessage}</div>}</div></div><button onClick={()=>handleDeleteDoc(doc.id)} className={`p-2 rounded-lg ${isDark?'hover:bg-red-500/10':'hover:bg-red-50'}`}><Trash2 size={16} className="text-red-400"/></button></div>))}</div>)}
      {activeTab==='upload'&&(<div className={`border-2 border-dashed rounded-2xl p-12 text-center ${isDark?'border-[#27272a]':'border-gray-300'}`}><Upload className={`mx-auto mb-4 ${textMuted}`} size={48}/><p className={`mb-2 ${text}`}>{t('knowledge.documents.dragDrop')}</p><p className={`text-sm mb-6 ${textMuted}`}>{t('knowledge.documents.supportedFormats',{size:'10'})}</p><input ref={fileInputRef} type="file" multiple accept=".pdf,.docx,.txt,.csv" onChange={handleFileUpload} className="hidden"/><button onClick={()=>fileInputRef.current?.click()} disabled={uploading} className="px-6 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-bold rounded-xl disabled:opacity-50">{uploading?t('common.loading'):t('knowledge.documents.upload')}</button></div>)}
      {activeTab==='url'&&(<div className={`rounded-2xl p-6 border ${card}`}><div className="flex gap-3"><input value={urlInput} onChange={e=>setUrlInput(e.target.value)} className={inputCls} placeholder={t('knowledge.url.placeholder')} dir="ltr"/><button onClick={handleAddUrl} disabled={!urlInput.trim()} className="px-6 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-bold rounded-xl disabled:opacity-50">{t('knowledge.url.crawl')}</button></div></div>)}
      {activeTab==='faq'&&(<div className={`rounded-2xl p-6 border space-y-4 ${card}`}><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('knowledge.faq.question')}</label><input value={faqQ} onChange={e=>setFaqQ(e.target.value)} className={inputCls}/></div><div><label className={`block text-sm mb-1 ${textMuted}`}>{t('knowledge.faq.answer')}</label><textarea value={faqA} onChange={e=>setFaqA(e.target.value)} rows={4} className={`${inputCls} resize-none`}/></div><button onClick={handleAddFaq} disabled={!faqQ.trim()||!faqA.trim()} className="px-6 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-bold rounded-xl disabled:opacity-50">{t('knowledge.faq.add')}</button></div>)}
      {activeTab==='search'&&(<div className="space-y-4"><div className="flex gap-3"><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&handleSearch()} className={inputCls} placeholder={t('knowledge.search.placeholder')}/><button onClick={handleSearch} disabled={searching||!searchQuery.trim()} className="flex items-center gap-2 px-6 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-bold rounded-xl disabled:opacity-50">{searching?<Loader2 size={16} className="animate-spin"/>:<Search size={16}/>}{t('common.search')}</button></div>{searchResults.length>0&&<div className="space-y-3"><h3 className={`font-medium ${text}`}>{t('knowledge.search.results')} ({searchResults.length})</h3>{searchResults.map((r,i)=>(<div key={i} className={`rounded-2xl p-4 border ${card}`}><div className="flex items-center justify-between mb-2"><span className={`text-xs ${textMuted}`}>{t('knowledge.search.source')}: {r.source}</span><span className="text-xs bg-teal-500/10 text-teal-400 border border-teal-500/20 px-2 py-0.5 rounded-full">{t('knowledge.search.score')}: {(r.score*100).toFixed(0)}%</span></div><p className={`text-sm leading-relaxed ${textSec}`}>{r.text}</p></div>))}</div>}</div>)}
    </div>
  );
}
