import { useState, useEffect } from 'react';
import { useLanguage } from '@/hooks/useLanguage';
import { useTheme } from '@/hooks/useTheme';
import { webhookAPI } from '@/services/api/publicAPI';
import { Webhook, Plus, Trash2, Play, Check, X, Loader2 } from 'lucide-react';
const EVENTS = ['call.completed','chat.ended','lead.created','extraction.completed','campaign.completed','handoff.created'];
export default function WebhooksPage() {
  const { t } = useLanguage(); const { isDark } = useTheme();
  const [endpoints, setEndpoints] = useState([]); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false);
  const [testing, setTesting] = useState(null); const [testResult, setTestResult] = useState(null);
  const [form, setForm] = useState({name:'',url:'',events:[],secret:''});
  useEffect(() => { loadEndpoints(); }, []);
  const loadEndpoints = async () => { try { setLoading(true); const res = await webhookAPI.getAll(); setEndpoints(res.data?.data||[]); } catch(e){console.error(e)} finally{setLoading(false)} };
  const handleCreate = async () => { if(!form.name||!form.url||form.events.length===0) return; try { await webhookAPI.create(form); setForm({name:'',url:'',events:[],secret:''}); setShowForm(false); loadEndpoints(); } catch(e){alert(e.message)} };
  const handleDelete = async (id) => { if(!confirm(t('common.confirm'))) return; try { await webhookAPI.delete(id); loadEndpoints(); } catch(e){console.error(e)} };
  const handleTest = async (id) => { try { setTesting(id); setTestResult(null); const res = await webhookAPI.test(id); setTestResult({id,...res.data?.data}); } catch(e){setTestResult({id,success:false,error:e.message})} finally{setTesting(null)} };
  const toggleEvent = (ev) => setForm(p=>({...p,events:p.events.includes(ev)?p.events.filter(e=>e!==ev):[...p.events,ev]}));
  const card = isDark ? 'bg-[#111113] border-[#1f1f23]' : 'bg-white border-gray-200';
  const text = isDark ? 'text-white' : 'text-gray-900'; const textSec = isDark ? 'text-gray-400' : 'text-gray-600'; const textMuted = isDark ? 'text-gray-500' : 'text-gray-500';
  const inputCls = `w-full rounded-xl px-4 py-2.5 border focus:border-teal-500 focus:outline-none ${isDark ? 'bg-[#1a1a1d] border-[#27272a] text-white' : 'bg-white border-gray-300 text-gray-900'}`;
  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6"><h1 className={`text-2xl font-bold ${text}`}>Webhooks</h1><button onClick={()=>setShowForm(!showForm)} className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 hover:from-teal-400 hover:to-cyan-400 text-white font-bold rounded-xl transition"><Plus size={16}/> إنشاء Webhook</button></div>
      {showForm&&<div className={`rounded-2xl p-6 border mb-6 space-y-4 ${card}`}><input value={form.name} onChange={e=>setForm(p=>({...p,name:e.target.value}))} placeholder="اسم الـ Webhook" className={inputCls}/><input value={form.url} onChange={e=>setForm(p=>({...p,url:e.target.value}))} placeholder="https://your-api.com/webhook" dir="ltr" className={`${inputCls} font-mono text-sm`}/><input value={form.secret} onChange={e=>setForm(p=>({...p,secret:e.target.value}))} placeholder="Secret (اختياري)" dir="ltr" className={`${inputCls} font-mono text-sm`}/><div><label className={`block text-sm mb-2 ${textMuted}`}>الأحداث</label><div className="flex flex-wrap gap-2">{EVENTS.map(ev=>(<button key={ev} onClick={()=>toggleEvent(ev)} className={`px-3 py-1.5 rounded-xl text-sm border transition ${form.events.includes(ev)?'bg-teal-500/10 text-teal-500 border-teal-500/20':isDark?'bg-[#1a1a1d] border-[#27272a] text-gray-400':'bg-white border-gray-200 text-gray-600'}`}>{ev}</button>))}</div></div><div className="flex gap-3 justify-end"><button onClick={()=>setShowForm(false)} className={`px-4 py-2 rounded-xl border ${isDark?'border-[#1f1f23] text-gray-400 hover:bg-[#1a1a1d]':'border-gray-200 text-gray-600 hover:bg-gray-50'}`}>{t('common.cancel')}</button><button onClick={handleCreate} disabled={!form.name||!form.url||form.events.length===0} className="px-4 py-2 bg-gradient-to-r from-teal-500 to-cyan-500 text-white font-bold rounded-xl disabled:opacity-50">{t('common.save')}</button></div></div>}
      <div className="space-y-3">{endpoints.map(ep=>(<div key={ep.id} className={`rounded-2xl p-5 border ${card}`}><div className="flex items-start justify-between mb-3"><div><div className={`flex items-center gap-2 mb-1 ${text}`}><Webhook size={16} className="text-teal-400"/><span className="font-medium">{ep.name}</span><span className={`text-xs px-2 py-0.5 rounded-full border ${ep.isActive?'bg-emerald-500/10 text-emerald-400 border-emerald-500/20':'bg-red-500/10 text-red-400 border-red-500/20'}`}>{ep.isActive?'نشط':'معطل'}</span></div><div className={`text-sm font-mono ${textMuted}`} dir="ltr">{ep.url}</div></div><div className="flex items-center gap-2"><button onClick={()=>handleTest(ep.id)} disabled={testing===ep.id} className={`p-2 rounded-lg ${isDark?'hover:bg-[#1a1a1d]':'hover:bg-gray-100'}`}>{testing===ep.id?<Loader2 size={16} className="animate-spin"/>:<Play size={16} className="text-emerald-400"/>}</button><button onClick={()=>handleDelete(ep.id)} className={`p-2 rounded-lg ${isDark?'hover:bg-red-500/10':'hover:bg-red-50'}`}><Trash2 size={16} className="text-red-400"/></button></div></div><div className="flex flex-wrap gap-1.5 mb-2">{ep.events?.map(e=><span key={e} className={`text-xs px-2 py-0.5 rounded-full border ${isDark?'bg-[#1a1a1d] border-[#27272a] text-gray-400':'bg-gray-50 border-gray-200 text-gray-500'}`}>{e}</span>)}</div><div className={`text-xs ${textMuted}`}>إجمالي: {ep.totalDeliveries} • نجاح: {ep.successCount} • فشل: {ep.failureCount}</div>{testResult?.id===ep.id&&<div className={`mt-3 p-3 rounded-xl text-sm border ${testResult.success?'bg-emerald-500/10 border-emerald-500/30 text-emerald-400':'bg-red-500/10 border-red-500/30 text-red-400'}`}>{testResult.success?<><Check size={14} className="inline me-1"/>نجح ({testResult.responseTime}ms)</>:<><X size={14} className="inline me-1"/>فشل: {testResult.error}</>}</div>}</div>))}{!loading&&endpoints.length===0&&<div className={`text-center py-12 ${textMuted}`}>لا توجد Webhooks</div>}</div>
    </div>
  );
}
